### ISSUE TITLE
Field text truncated in SQL database

### ISSUE THREAD

**Issue by Tupperware69** [ruben2020/codequery#58]
I am seeing function call text truncated in the SQL database (limit 80 chars?) when compared to cscope.out.  Can this be extended/removed? I didn't see anything obvious in the source code.

**Comment by ruben2020** [comment]
Hi @Tupperware69 
You are right. It can be extended or removed. I'll look into it.
Thank you for the request.

**Comment by ruben2020** [comment]
Fixed in the `develop` branch. However, the CLI `cqsearch` still truncates to 80 characters unless you use the new `-l` option in the argument.

**Comment by ruben2020** [comment]
Now officially released in v0.19.0. This would also be of interest to @devjoe who uses `cqsearch` for vim-codequery. `cqsearch` still truncates to 80 characters by default in order to maintain backward compatibility. But there is a new `-l` option in the argument to make it unlimited or set a limit.
In CodeQuery GUI, there is no limit.
