### ISSUE TITLE
How do you view the call graph?

### ISSUE THREAD

**Issue by pakdev** [ruben2020/codequery#66]
I followed the Windows HOWTO and can browse my source after loading myproject.db. However, the "Draw graph" button is permanently grayed out. How do I enable this button to conceivably generate call graphs?

**Comment by pakdev** [comment]
Ah, I figured it out. To make the button work, you have to select one of the drop downs that includes the text "(Graph Available)" and then execute another search. Simply changing the dropdown and even clicking results is not sufficient to enable the button. This should be fixed.

**Comment by pidgeon777** [comment]
> Ah, I figured it out. To make the button work, you have to select one of the drop downs that includes the text "(Graph Available)" and then execute another search. Simply changing the dropdown and even clicking results is not sufficient to enable the button. This should be fixed.

I second this.

**Comment by ruben2020** [comment]
@pakdev @pidgeon777 Now this is fixed in the develop branch.

When you change the drop down box selection for query type, it will search immediately. When the search results are displayed, the first result will be automatically be selected / highlighted, and the graph generation capability will be enabled, if you had selected one of those query types with "(Graph Available)".
