### ISSUE TITLE
[Enhancement] Update of cscope to 15.9 version

### ISSUE THREAD

**Issue by pidgeon777** [ruben2020/codequery#81]
Cscope version 15.9 is out with different improvements, I would suggest codequery to also include it.

**Comment by ruben2020** [comment]
@pidgeon777 Thank you. I will include it. Actually, it should work out of the box with CodeQuery, but I'll test it.

**Comment by pidgeon777** [comment]
Great, thank you.

**Comment by ruben2020** [comment]
Hi @pidgeon777 
CodeQuery works out of the box with cscope 15.9 in Linux.

However for Windows, there are no official binaries available for cscope 15.9 [here](https://code.google.com/archive/p/cscope-win32/), and I discovered that the task to port cscope 15.9 to Win32 is relatively difficult because cscope was not originally written in a way that is multi-platform friendly unlike CodeQuery.

Also, I don't want to take a risk as the cscope 15.8a Win32 binaries included with CodeQuery works perfectly fine for all use cases. Hence, I will keep it for the CodeQuery Win32 installer, rather than introduce a buggy Win32 port of cscope 15.9.
